

// MATERI DATABASES


//! 1. APA ITU DATABASE
/*
    DATABASE ADALAH SEBUAH TEMPAT DIMANA SEKUMPULAN DATA DAN INFORMASI DISIMPAN
*/


//! 2. APA ITU DBMS
/*
    * DBMS ADALAH DATABASE MANAGEMENT SYSTEM SEBUAH APLIKASI UNTUK MEMBUAT,MENGELOLA DAN MENGAMANKAN DATA

    * CONTOHNYA SEPERTI MYSQL, POSTGRE, MARIADB, MONGODB
*/

//! 3. JENIS-JENIS DBMS
/*
    TODO: ADA 2 JENIS DMBS

    * 1. RDBMS (RELATIONAL DATABASE MANAGEMENT SYSTEM)
      * SEBUAH DATABASE YG DIBUAT ATAU DISIMPAN DI DALAM TABLE YG DIMANA ADA COLUMN DAN JUGA BARIS
      *
      * CONTOHNYA : MARIADB,MYSQL,POSTGREE


    * 2. NO-RDBMS (NON-RELATIONAN DATABASE MANAGEMENT SYSTEM)
      * SEBUAH DATABASE YG DIBUAT DI DALAM FILE JSON DENGAN BENTUK OBJECT ATAU PERPASANGAN ANTARA KEY DAN JUGA VALUE
      * 
      * 
*/

// TODO: SQL ADALAH STRUCTURED QUERY LANGUAGE SEBUAH BAHASA YG DIGUNAKAN UTNUK BERINTERAKSI DENGAN RELATIONAL DATABASE

//! 3. PERINTAH SQL SEDERHANA UNTUK BERINTERAKSI DENGAN RDBMS
/*
    * 1. create database nama_database = untk membuat database
    * 2. drop database nama_database = untuk menghapus database
    * 3. use nama_database = untuk menggunakan database
*/


//! 4. TIPE DATA YG ADA DI DATABASE
/*
    TODO: TIPE DATA ADALAH JENIS DATA YG AKAN DI SIMPAN DI DALAM SEBUAH TABLE ATAU COLUMN
    
    * 1. NUMBER
      /
        * 1.1 INTEGER || INT
          * DIGUNAKAN UNTUK MENYIMPAN DATA BILANGAN BULAT
          * CONTOHNYA PILIHAN INT: TINYINT, SMALLINT, MEDIUMINT, INT, BIGINT
        
        *. 1.2 FLOATING POINT 
           * DIGUNAKAN UNTK MENYIMPAN DATA BILANGAN PECAHAN
           * CONTOH PILIHANNYA: FLOAT, DOUBLE
        
        *. 1.3 DECIMAL 
           * DIGUNAKAN UNTK MENYIMPAN DATA BILANGAN YG DIMANA PANJANG ANGKANYA BISA DITENTUKAN
           * CONTOH PILIHANNYA: DECIMAL(PANJANG_NUMBERNYA,PANJANG_ANGKA_SETELAH_KOMA)
      / 

    * 2. STRING -> TIPE DATA UNTUK  MENYIMPAN DATA KARAKTER
      /
        TODO: NOTE: MAKSIMAL UKURAN PANJANG KARAKTER DI CHAR DAN VARCHAR ITU 65535 
        * 2.1 CHAR(PANJANG_KARAKTER (OPTIONAL)) 
          * TIPE DATA STRING UNTUK MENENTUKAN PANJANG KARAKTER
           
        * 2.2 VARCHAR(PANJANG_KARAKTER (OPTIONAL))
          * TIPE DATA STRING UNTUK MENENTUKAN PANJANG KARAKTER
        
        * 2.3 TEXT
          * TIPE DATA STRING YANG PANJANG KARAKTERNYA SUDAH DI TENTUKAN
          * CONTOH PILIHANNYA: TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT
        
        * 2.2 ENUM
          * TIPE DATA STRING UNTUK MENENTUKAN OPSI ATAU PILIHAN DATA APA YG BOLEH DI MASUKAN
          * CONTOHNYA : ENUM('PRIA','WANITA') -> INI ARTINYA KITA AKAN SET SEBUAH COLUMN HANYA BOLEH DI MASUKAN DATA PRIA ATAU WANITA
          
      / 

    * 3. DATE AND TIME -> TIPE DATA UNTUK  MENYIMPAN DATA TANGGAL DAN WAKTU
      /
        * 3.1 DATE
          * TIPE DATA DATE UNTUK MENYIMPAN DATA HANYA TANGGALNYA -> YYYY-MM-DD
        
        * 3.1 DATETIME
            * TIPE DATA DATE UNTUK MENYIMPAN DATA  TANGGAL DAN WAKTU -> YYYY-MM-DD HH-MM-SS
        
        * 3.1 TIMESTAMP
            * TIPE DATA DATE UNTUK MENYIMPAN DATA  TANGGAL DAN WAKTU KETIKA DATANYA DI MASUKAN-> YYYY-MM-DD HH-MM-SS
        
        * 3.1 TINE
            * TIPE DATA DATE UNTUK MENYIMPAN DATA WAKTU SAJA->  HH-MM-SS
        
        * 3.1 YEAR
            * TIPE DATA DATE UNTUK MENYIMPAN DATA  TAHUN SAJA-> YYYY

      /

    * 3. BOOLEAN  -> TIPE DATA UNTUK  MENYIMPAN DATA KEBENARAN ADANYA TRUE DAN FALSE


*/