

--! materi join di table relationship

--! 1. APA ITU JOIN
/*
    --? JOIN ADALAH SEBUAH TEKNIK ATAU CARA UNTUK MENGAMBIL ATAU SELECT DATA DARI 2 ATAU LEBIH TABLE 
    TODO: JADI KITA BISA NGAMBIL DATA DARI TABLE BUKU DAN TABLE PENULIS MISALNYA
*/ 