
-- PERINTAH DATABASES
/*
    ? CREATE DATABASE NAMA_DATABASE; --> UNTUK MEMEBUAT DATABASE
    ? SHOW DATABASES; --> UNTUK MELIHAT DATABASE APA AJA YG ADA
    ? USE NAMA_DATABASE; ---> UNUTK MENGGUNAKAN SEBUAH DATABASE
    ? DROP DATABASE NAMA_DATABASE --> UNTUK MENGHAPUS DATABASE
    
*/