--! MATERI BASIS DATA

--! 1. APA ITU BASIS DATA
/*
BASIS DATA ATAU DATABASE ADALAH SEKUMPULAN DAN INFORMASI YG DI SIMPAN DAN DI KELOLA DISEBUAH TEMPAT ATAU MEMORY
*/
--TODOl INTINYA DATABSE SEBUAH TEMPAT DI MANA DATA DAN INFORMASI DI SIMPAN DAN DI KELOLA

--TODO: NOTES: TUJUAN BASIS DATA ADALAH UNTUK MENGELOLA , MENGELOMPOKAN SEKUMPULAN DATA YG BAIK AGAR MEMPERMUDAH KITA SAAT MENGAKSES DATA

--! 2. SISTEM BASIS DATA || DATABASE MANAGEMENT SYSTEM
/*
DBMS ADALAH SEBUAH SISTEM ATAU APLIKASI UNTUK MEMBUAT,MENGAMANKAN DAN MENGELOLA DATA DI KOMPUTER
*/

--! 2.1 CONTOH-CONTOH DBMS
/*

--TODO: ADA BEBERAPA JENIS 

--TODO: JENISH END USER
/
* 1. MICROSOFT EXCEL
* 2.  MICROSOFT ACCESS
* 3. GOOGLE DOCS 
* ...DLL
/   

--TODO: LINGKUP DI PROGRAMER
/
    * 1. MYSQL
    * 2. MARIADB
    * 3. POSGREE
    * 1. SQL SERVER
    ...DLL

/

*/


-- ! 3. JENIS JENIS BAHASA DATABSE
/*
    TODO: NOTES BAHASA DATABASE ADALAH BAHASA YG DIGUNAKAN UNTUK BERINTERAKSI DENGAN DATABASE

    * 1. DDL ( DATA DEFINITION LANGUAGE )
    /
        * SEBUAH BAHASA YG DIGUNAKAN UNTUK MENDIFINSIKAN SESUATU ATAU MEMBUAT STRUKTUR DATABSE YG DIBUAT
        TODO: CONTOH KAYA MEMBUAT DATABASE TABLE ATAU COLUMN YG ADA DI DALAM TABLE, MENGUBAH TABLE ATAU COLUMN YG ADA DI DALAM TABLE
    / 

    * 2. DML ( DATA MANIPULATION LANGUAGE)
    /
        * SEBUAH BAHASA YG DIGUNAKAN UNTUK MENGELOLA DATA YG ADA DI DALAM TABLE PADA DATABSE
        TODO: CONTOH KAYA MENGAMBIL, MENAMBAHKAN, MENGUPDATE DAN MENDELETE DATA DALAM  TABLE 

    /
*/

--! 4. MODEL DATA
/*
    TODO: MODEL DATA ADALAH  KUMPULAN KONSEPTUAL UNTUK MENGGAMBARKAN DATA, HUBUNGAN DATA DAN BATASAN DATA
    TODO: TUJUANNYA ADALAH AGAR KITA BISA TAHU MAKNA ATAU TUJAN DARI DATA DAN JUGA RELASI ANTAR DATANYA
*/

--! 5. ERD  (ENTITY RELATIONSHIP DIAGRAM)