--! MATERI BASIS DATA

--! 1. APA ITU BASIS DATA
/*
BASIS DATA ATAU DATABASE ADALAH SEKUMPULAN DAN INFORMASI YG DI SIMPAN DAN DI KELOLA DISEBUAH TEMPAT ATAU MEMORY
*/
--TODOl INTINYA DATABSE SEBUAH TEMPAT DI MANA DATA DAN INFORMASI DI SIMPAN DAN DI KELOLA

--TODO: NOTES: TUJUAN BASIS DATA ADALAH UNTUK MENGELOLA , MENGELOMPOKAN SEKUMPULAN DATA YG BAIK AGAR MEMPERMUDAH KITA SAAT MENGAKSES DATA

--! 2. SISTEM BASIS DATA || DATABASE MANAGEMENT SYSTEM
/*
DBMS ADALAH SEBUAH SISTEM ATAU APLIKASI UNTUK MEMBUAT,MENGAMANKAN DAN MENGELOLA DATA DI KOMPUTER
*/

--! 2.1 CONTOH-CONTOH DBMS
/*

--TODO: ADA BEBERAPA JENIS 

--TODO: JENISH END USER
/
* 1. MICROSOFT EXCEL
* 2.  MICROSOFT ACCESS
* 3. GOOGLE DOCS 
* ...DLL
/   

*/